#!/bin/bash

set -o errexit
set -o xtrace
set -o nounset

INPUT=/bbx/input/assembler.yaml
READS=$(yaml2json < ${INPUT} \
        | jq --raw-output '.arguments[] | select(has("fastq")) | .fastq[].value | "-short \(.)"' \
        | tr '\n' ' ')


# Location where to assemble reads
TMP_DIR=$(mktemp -d)

velveth ${TMP_DIR} 31 -fastq.gz ${READS}
velvetg ${TMP_DIR} -cov_cutoff

cp ${TMP_DIR}/contigs.fa /bbx/output
