#!/bin/bash

set -o errexit
set -o xtrace
set -o nounset

READS=$(mktemp)

# Concatenate gzipped fastq files together
cat ${CONT_FASTQ_FILE_LISTING} | tr "\n" " " | xargs cat > ${READS}

# Location where to assemble reads
TMP_DIR=$(mktemp -d)

# Determine which process to run
CMD=$(egrep ^${TASK}: /Taskfile | cut -f 2 -d ':')

if [[ -z ${CMD} ]]; then
  echo "Abort, no task found for '${TASK}'."
  exit 1
fi
eval ${CMD}

cp ${TMP_DIR}/contigs.fa ${CONT_CONTIGS_FILE}
